### ISSUE TITLE
Is there any way to control the speaker volume, e.g., Sonos

### ISSUE THREAD

**Issue by RobertBernstein** [dheijl/swyh-rs#113]
This app works great!  I would love to be able to control the speaker output of my Sonos speakers using the Windows volume control or a volume control within the swyr-rs GUI.  In order to control the volume, I need to open the Sonos app and adjust it there.  Any suggestions?

Thanks!

**Comment by dheijl** [comment]
It is certainly feasible to control the volume using dlna, the problem is that I hate gui design, and that I don't see myself making the necessary gui changes. The logic for changing the volume is  quite simple if I remember correctly. I'll give it a thought but don't hold your breath...
Would a right click on a player button with a popup showing a volume slider be acceptable?

**Comment by RobertBernstein** [comment]
Right-clicking on a player button would be great.  Thanks for even considering this.

**Comment by dheijl** [comment]
OK but this could take some time...

**Comment by dheijl** [comment]
This is probably be what you will get (WIP): 

![afbeelding](https://github.com/dheijl/swyh-rs/assets/2384545/cdb39f84-e24f-4cfb-a00f-cff09efb6f97)

Apparently the values as reported by UPNP/DLNA are not very accurate, but they are close enough.

**Comment by RobertBernstein** [comment]
That looks really good.

**Comment by dheijl** [comment]
Release 1.9.5 should fix this issue.
