### ISSUE TITLE
Volume Setting Question - Sonos Protocol

### ISSUE THREAD

**Issue by omoknen** [dheijl/swyh-rs#115]
SWYH-RS V1.9.5
Windows 10
Sonos Speakers

I have a question about the sliders.  I have a set of Sonos speakers, and when I brought up the new version, the sliders were all low for the volume.  The Speakers themselves had all their previous volume and the Sonos application showed the correct volume and could change them.

Are the sliders for all protocols or are the sliders only for UpMPD protocol devices I saw on the screenshot on the feature request.

I am okay with using my Sonos speakers without the sliders.  I have had Sonos speakers crash and they are kind of a pain to restart which is why I am asking.

Thank you

**Comment by dheijl** [comment]
As I don't have Sonos myself I can't really answer your question. I try to get/set the volume using the documented upnp/dlna way, but many devices behave in a non-standard way.
It would be helpful if you could activate debug mode in 1.9.5 and attach the log file here, so that I can see what happens, even if you don't try to use the sliders to change the volume.
Perhaps Sonos does not support the upnp Volume service.

**Comment by omoknen** [comment]
I will do that tomorrow, and I will upload it then.  Thank you.

**Comment by omoknen** [comment]
I know our anti-tinnitus system has a bunch of refurbished Sonos with a new Sonos, but they all don't register the volume from looking at the log.  Thanks for being so quick.

[log.txt](https://github.com/dheijl/swyh-rs/files/14169540/log.txt)

**Comment by dheijl** [comment]
Thanks for the log. It confirms what I read elsewhere: recent Sonos firmware is gradually phasing out UPNP/DLNA support.
A recent update enabled FLAC support, but apparently other stuff has to go...
For instance [Sonor](https://github.com/jakobhellermann/sonor) has been abandoned because recent Sonos devices no longer work with it.
I'll publish 1.9.6 shortly, it will no longer show the sliders if they don't work.

**Comment by dheijl** [comment]
Thanks,I'll close this then.

**Comment by omoknen** [comment]
Hi.  I assumed you wanted me to try the new 1.9.7-beta version.  Yes, it does show the volume control for the Sonos as well as it allows you to manipulate the problem.   It was a present surprise.

**Comment by dheijl** [comment]
Thanks for the feedback and for trying it out!
