### ISSUE TITLE
V0.9.0 deb

### ISSUE THREAD

**Issue by MX10-AC2N** [dheijl/swyh-rs#12]
C:\Users\Asus-AC2N> cd desktop\swyh-rs

C:\Users\Asus-AC2N\Desktop\SWYH-RS>swyh-rs-deb
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "Le chemin d’accès spécifié est introuvable." }', src\main.rs:144:77
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

C:\Users\Asus-AC2N\Desktop\SWYH-RS>

**Comment by dheijl** [comment]
Is already fixed in source but not yet released.
As a work-around you can delete the swyh-rs folder in your home directory (c:\users\\{user_name}\swyh-rs).
The reason: a mistake in the default setting for a new configuration setting. Sorry about that.
I will release the new version in about half an hour or so...

Sorry about that!

**Comment by dheijl** [comment]
The new release 0.9.1 should fix it (I hope).

**Comment by MX10-AC2N** [comment]
V0.9.1 work great !! Thanks..

**Comment by MX10-AC2N** [comment]
I take this opportunity to add a small request .. It would be good to be able to restart a scan of the different upnp renderer available directly from swyh-rs without having to restart swyh-rs.. thanks again

**Comment by dheijl** [comment]
I know, but that is quite some work mainly because the entire GUI has to be redrawn from scratch (buttons can disappear and others can appear, everything beneath them has to move up or down...).

I would first have to redesign the GUI before I can add that, perhaps adding the discovery as a last step instead of as the first step, that would make things a lot easier.

There's also the consistency to consider: what if a renderer does not respond in time to be discovered although it is still streaming? This *does* happen now and then, and the streaming runs totally independent of the rest of the program, in a separate thread.

But I have considered it, and it's a valid request.

**Comment by dheijl** [comment]
I'm considering running SSDP discovery automatically in the background at a set time interval, like every x minutes.
What would you find a good time interval?

Or would you prefer an "SSDP discovery update" button?

**Comment by MX10-AC2N** [comment]
I was thinking more of a button, I think that the automatic search at regular intervals will require regular access to system resources and that this will weigh down the application during its use, it is preferable to keep the use as light as possible at the level System resources ...

**Comment by dheijl** [comment]
Too bad ... you're too late. It's in there already in V 0.9.2, so you can test it.
And it should not use any significant resources.

**Comment by MX10-AC2N** [comment]
V 0.9.2 tested, work fine..! Great Job like always.. ;-)
