### ISSUE TITLE
Vu-meter for streamed output

### ISSUE THREAD

**Issue by MX10-AC2N** [dheijl/swyh-rs#13]
Hi, 
Would it be possible to add a vu-meter giving the level of the streamed output ? 
A quick idea for GUI..
![Swyh-rs](https://user-images.githubusercontent.com/62643837/96731909-114b7480-13b8-11eb-9569-d9ff7390ab9a.jpg)

**Comment by dheijl** [comment]
You have obviously a lot more talent than I have in GUI design, but there are two reasons that I'm not inclined to do it:

- I hate GUI programming, I write this for fun, and I don't see the fun in implementing fancy GUIs
- it serves no real purpose aside from being pleasing to the eye
- it takes CPU for measuring the magnitude of the samples that are being streamed and it takes even more CPU to render it in the GUI

If you see a fancy GUI you can be sure that it wasn't made by me!

About VU-meters:

On Wed, Sep 25, 2002 at 09:12:22 +0100, Bob Ham wrote:
> On Wed, 2002-09-25 at 15:38, Steve Harris wrote:
> > I know a VU meter in a PCM system is about as much use as an underwater
> > hairdryer
>
> I don't know. Why is useless? :)
Because vu meters only give you an idea of the average amplitude over a
fairly long time, and say nothing about peaks, so there no good for
detecting 'overs' in digital systems.
However if you're using jack to feed 1/2" tape or broadcast FM then the're
possibly useful.
Hands up all those who record to multitrack analogue tape ;)

Sorry...

**Comment by dheijl** [comment]
It's not exactly what you had in mind but it's something!  

release [1.3.6](https://github.com/dheijl/swyh-rs/releases/tag/1.3.6)

![alt_tag](https://user-images.githubusercontent.com/2384545/108632396-fcb6e000-746e-11eb-9a9a-8d4eaf1cf010.PNG)
