### ISSUE TITLE
Loop stream loss

### ISSUE THREAD

**Issue by MX10-AC2N** [dheijl/swyh-rs#20]
Hi @dheijl I have installed the latest version 1.0.4 ..
This several times that I find this problem of loss of the stream, at the beginning you had thought that my amplifier cut the transmission as soon as a silence was detected and suddenly you had coded us the autoresume play, it works well in general but sometimes without my understanding why the stream is systematically interrupted, without there being any silence since I am reading music, the autoresume works and suddenly I find myself with a stream systematically interrupted then restart. .. Endlessly...
I wonder why my amp decides to stop the stream?
Why this problem only occurs from time to time ... for info I had run swyh-rs without my amp being turned on so I started without any visible renderer then I turned on my amp, swyh-rs detected my amp, I started the stream with the autoresume checked (as usual) and this problem occurred ... I restart swyh-rs but same problem many times, I stop swyh-rs, I start LAB, I start the stream and there is no problem, stream continuously ... I stop LAB and restart swyh-rs and there magic no more cutting the stream ... I don't understand anything. .. But there is something ...

**Comment by dheijl** [comment]
Hi @MX10-AC2N ,

The problem is that I have no idea why the amp decides to drop the streaming connection. The main difference between LAB and swyh-rs is that LAB subscribes to the dlna events of the amplifier and swyh-rs does not. But LAB uses the unmaintained memory leaking Intel DLNA library for that, and I use no external library, and implementing this is a *lot* of work and it should not be necessary, it is only an option in dlna.

What could possibly help is a network sniffer trace of a session that has the streaming interruption problems. For that you would have to install Wireshark and trace the network traffic while the problems occur, after that you save the trace file (pcap format) and attach it here. There *might* be something of interest to see, but then again there may be not...

**Comment by MX10-AC2N** [comment]
Thank, I will try Wireshark, we'll see..

**Comment by dheijl** [comment]
Before you start with Wireshark I'd like to test something first and make a change with a new prerelease if my suspicion is correct...

**Comment by MX10-AC2N** [comment]
Other details when I stream with swyh-rs my amp displays nothing, while if I use L.A.B. my amp displays Local Audio Broadcast .. What is strange is that my amp continues to display Local Audio Broadcast even though I reuse swyh-rs ...
I wait for the problem to come back and I will post the Wireshark file ...

**Comment by dheijl** [comment]
The display from LAB is probably because it publishes a metadata URL although there is no metadata available for the music stream.

**Comment by MX10-AC2N** [comment]
Hi Dheijl, 
This morning when I launched swyh-rs I found this problem .. So I made a copy with Wireshark here is the file I got.
[mx10.zip](https://github.com/dheijl/swyh-rs/files/5579290/mx10.zip)

**Comment by dheijl** [comment]
Thanks! I'll have a look asap.

**Comment by MX10-AC2N** [comment]
another file when the stream is OK..
[mx10_good_stream.zip](https://github.com/dheijl/swyh-rs/files/5579325/mx10_good_stream.zip)

**Comment by dheijl** [comment]
OK thanks I'll let you know if I find something.

**Comment by dheijl** [comment]
What I see in the "bad" capture:

- at a certain point your HK AVR, without any obvious reason, decides that it wants to terminate the connection and sends a "FIN/ACK" packet on the first ethernet packet of an 8 KB TCP chunk of audio data, and then sends a "RST" packet to the remaining ethernet packets of the chunk, as it has to do in such a case
- at this point the PC too terminates the TCP connection (it's only doing what it has been told by the AVR)
- what is strange but apparently not abnormal in network traces: the "ACK/FIN" packet is sent before the packet that it is acknowledging has been sent according to the wireshark trace   

So we have learned exactly nothing, except that we are sure that at a certain point the AVR decides it's had enough for whatever reason. 

Perhaps you could take a trace of a LAB session too, just to see if it uses another (better suited?) chunk size instead of the 8KB chunks that swyh-rs sends? There must be reason for the disconnection, but it's not visible in the network trace.

And thanks for helping me track this down!

**Comment by MX10-AC2N** [comment]
[LAB.zip](https://github.com/dheijl/swyh-rs/files/5579484/LAB.zip)

**Comment by dheijl** [comment]
Thanks, but could you include the starting of the session with LAB? 
I think it does not use use chunked transfer at all but can't be sure because I don't have the beginning of the stream.

**Comment by MX10-AC2N** [comment]
[LAB1.zip](https://github.com/dheijl/swyh-rs/files/5579522/LAB1.zip)

**Comment by dheijl** [comment]
Thanks, it does indeed not use chunked transfer, but specifies an enormous length instead (9223372036854775807 octets). This is something you are not supposed to do if you don't know the length, you are supposed to switch to chunked transfer instead...

> HTTP/1.1 200 OK
> TransferMode.DLNA.ORG: Streaming
> Server: UPnP/1.0 DLNADOC/1.50 LAB/1.0
> icy-name: Local Audio Broadcast
> Date: Sun, 22 Nov 2020 13:02:08 GMT
> Content-Length: 9223372036854775807
> Content-Type: audio/L16;rate=48000;channels=2
> Connection: close
> 

In fact, the HTTP server that I use switches to chunked transfer automatically when streaming, it's not something I can control. 
So it looks like your AVR has a problem with chunked transfer...

I'll have to thunk about a solution...

**Comment by MX10-AC2N** [comment]
However swyh-rs generally works well, I use it from morning until night without a problem.
Chunked transfer therefore generally works well ...
Maybe the fact that there is no Metadata in the stream is blocking something in my amp, wouldn't it be possible to add a fake metadata in the stream, like <SWYH-RS Stream from 'IP '>
Thank again

**Comment by dheijl** [comment]
I did not see any metadata requests or metadata information from LAB either, I think it's the Intel Microstack software in your AVR that has a problem with HTTP chunked encoding...

**Comment by MX10-AC2N** [comment]
Yes it is an old AVR and indeed it was perhaps not really intended for this kind of use, I hope that this will solve some compatibility problems on the old AVRs...
 :-)

**Comment by dheijl** [comment]
Unfortunately I can't disable chunked transfer in the  built-in webserver. If I do it blows up (eats all the RAM of the PC) because it tries to buffer the whole stream and never sends anything because the audio stream does never end...

**Comment by dheijl** [comment]
https://github.com/dheijl/swyh-rs/releases/tag/1.0.9-beta

You can now disable chunked transfer encoding, maybe this will solve your problem?

I had to patch the HTTP server I use (tiny-http) to make this possible.

**Comment by MX10-AC2N** [comment]
Hi Dheijl, and another mega BRAVO for everything you've coded with SWYH-RS.
So that's great, thanks to the new 'Disable Chunked Transfer' function I don't even need to activate the 'Autoresume play' function anymore.
It works really well, I'll let the stream run a bit and I'll keep you posted.
Really you are at the TOP ..!

**Comment by MX10-AC2N** [comment]
And other good news with the 'Disable chunked Transfer' function, I was able to reconfigure the VB-Audio virtual sound card in 44100Hz without this creating any interference in the stream, my physical sound card is in 48000Hz 16Bits and I can not modify its parameters .. Before I had to configure VB-Audio in 48000Hz so that the stream is not noisy ...
This V1.0.9 seems to provide good solutions for old AVRs .. Superb update ... ;-)

**Comment by dheijl** [comment]
I'm glad to hear that it was indeed the chunked transfer that caused your problems!

**Comment by MX10-AC2N** [comment]
Yes, another issue that you can close, great job..
