### ISSUE TITLE
Provide a server mode for devices that are not renderers (SWYH feature parity)

### ISSUE THREAD

**Issue by instinctualjealousy** [dheijl/swyh-rs#39]
The original SWYH provides a server accessible by Media Players as well as the traditional Stream To/PlayTo mode of pushing to Renderers. When SWYH is running, the audio stream is also exposed as two "songs" for the different codecs the original SWYH supports, which any player can access (theoretically, as I'm having an issue with theirs, and I think it's an implementation issue).

This would be useful to me because of [this](https://github.com/StreamWhatYouHear/SWYH/issues/45#issuecomment-829045777), but it would be useful for situations where the target device does not support rendering *at all*. It'd make this project an even more complete replacement. Sorry for the trouble. (=

[See also](http://www.streamwhatyouhear.com/getting-started/): "If the device is an UPnP/DLNA Media Player" section.

**Comment by dheijl** [comment]
swyh-rs already provides a web server for accessing the stream at _http://{ip}:5901/stream/swyh.wav_, so that you can define it as a "web radio stream" in your renderer in case it does not support DLNA "pushing".

You can even download this stream from a browser should you want to do so, and get a file called _swyh.lpcm_.

This has always been the case in swyh-rs, and is also documented in the Readme.

The streaming format is PCM/L16, optionally with a WAV header of inifinite length (the original SWYH does not have this WAV header option). The only difference here with SWYH is that I do not support transcoding the audio stream to MP3. 

In the latest release the port number (default 5901) can be changed.

**Comment by instinctualjealousy** [comment]
HTTP Live Streaming, right? That's listed under "If the device doesn’t support the DLNA" for the original SWYH. If it doesn't provide a device for the Xbox 360 connect to and expose the stream from, I don't think it'd be possible to connect it with this by itself. My usecase might just be too weird to be worth implementing this, as HTTP Live Streaming would probably cover the other 99% for most people.

If only MS didn't lock down media renderer mode to single task. I have no clue why they did that. It's a far more graceful way of doing it and would easily work with both SWYH's with no problems. The only reason I need these weird workarounds is because of that. I might see what I can rig up though.

**Comment by dheijl** [comment]
You could use the free VLC app to listen to the network media stream on the Xbox, using the WAV header option.
But I don't know about the "background music" possibilities using VLC, as I've never set eyes on a Xbox.

**Comment by dheijl** [comment]
I assume it works for you now, so I'm closing this.
