### ISSUE TITLE
Adding functionality "Record what you hear"?

### ISSUE THREAD

**Issue by Fonti68** [dheijl/swyh-rs#44]
Hi and first of all thanks for your nice work :-)

Do you have a plan to add also the functionality "Record what you hear", preferably without a file size restriction?

In the original "SWYH" there's a file size limit which is sad since every time I record a long audiobook for later offline-hearing the recording stops after approx. 3 hours...

Thanks again and best regards

**Comment by dheijl** [comment]
I have no such plans, mainly because I do not want to add audio encoding. It would be easy to add recording the audio in LPCM or WAV format, but the recorded files would be *huge*. 
Have you considered Audacity (https://www.audacityteam.org/)? It can do recording in any format you want for as long you want provided you have the disc space. 
https://manual.audacityteam.org/man/tutorial_recording_computer_playback_on_windows.html should get you going.

**Comment by Fonti68** [comment]
Thanks for your fast reply... impressed indeed! 👍 
The reason I came across SWYH is that only this fancy little tool allowed to record directly from my stream... I tried Audacity but probably I didn't dig deep enough in the settings... RTFM... :-)
Thanks a lot anyway!

**Comment by Fonti68** [comment]
Me again: thanks for guiding me to the correct tutorial - had to add the VB-Audio virtual app since I couldn't choose Stereo-mix...

**Comment by dheijl** [comment]
I added a note to the readme about recording with Audacity, so I'm closing this now.
