### ISSUE TITLE
Stereo pair for Sonos adds extreme latency compared to just using one speaker

### ISSUE THREAD

**Issue by Max3651** [dheijl/swyh-rs#72]
Hello, I’ve been using this software for a week now on my Sonos one speaker and it worked so much better than every other alternative. I recently decided to add a stereo pair and it sound so much better, but the latency while using swyh-rs is much worse. It feels weird watching movies and video game’s are unplayable. Flac doesn’t work so I can only use .wav, 24 bit adds more latency. Since my speakers are wireless I can’t change group delay or anything and I’ve tried lowering the frequency in windows settings from 48000 to 44100 and I didn’t see any improvement. Help would be greatly appreciated

**Comment by dheijl** [comment]
I'm afraid that swyh-rs can not really be used to stream the audio that comes with video or gaming. Although swyh-rs itself uses minimal buffering (typically around 8 KB depending on the buffer size used by the OS), the receiving devices like your Sonos *have* to introduce some substantial (usually configurable) buffering to cope with networking latency and so avoiding drop-outs.
You really need a "hardware" connection to the player, like HDMI, to keep audio and video synchronized, unless your video/gaming software allows you to delay the video stream with a certain "offset" so that the audio can keep up with the video.
One application that allows this is VLC, but I have no idea if there are others.  
There is really nothing that can be done on the swyh-rs side: I can't send the audio before I have received it from the OS...

**Comment by Max3651** [comment]
Installing the oldest version made the latency much better while using stereo pair. I think when I have the chance I’m going to download newer and newer versions until the latency issue comes back, I can update you on that if you would like.

**Comment by dheijl** [comment]
That would be interesting to know, because the audio capture and the streaming have not really been changed for ages.
What has been updated are the libraries I use like CPAL (audio capture)  and tiny-http (streaming server).
