### ISSUE TITLE
Audio stuttering after an irregular number of SSDP Discoveries 

### ISSUE THREAD

**Issue by beWAYNE** [dheijl/swyh-rs#75]
On my SONOS, audio stuttering occurs after an undetermined number of SSDP Discoveries. The workaorund here is that when the stuttering starts, I disconnect from the Sonos renderer and reconnect.

For example, on the 4th SSDP Discovery, the stuttering started at 07:41 (ssdp_interval_mins: 5.0). Attached is my log.
[log.txt](https://github.com/dheijl/swyh-rs/files/9450817/log.txt)

**Comment by dheijl** [comment]
I doubt that ssdp discovery has anything to do with it, but to make sure, could you set the ssdp interval to a very high value, like a couple of hours, and test again?
I would be inclined to suspect network latency combined with a very low amount of buffering at the Sonos side. Swyh-rs does not do any buffering except when the receiving device is slow in accepting frames, which is unlikely because audio bitrates are really low compared to the throughput of a decent network.

**Comment by dheijl** [comment]
Closing - lack of activity or feedback

**Comment by beWAYNE** [comment]
Sorry for the long wait.
I found that I had the same problem as #84. Thanks to an update, it is now possible to use SONOS speakers via the FLAC audio format. So far no more audio stuttering, probably because there is now a small buffer. I only have this 5 second buffer with the FLAC format, before I could only use WAV.
I don't know if that's the reason, it's just a theory at the moment.

**Comment by dheijl** [comment]
Thanks for the feedback! I'll add that to the documentation for Sonos. Could you give me the details of the Sonos update (version number) that enables FLAC on the Play 1?

**Comment by beWAYNE** [comment]
Unfortunately I can't say for sure. Coincidentally, I tried the FLAC format again, as it is supposed to fix all stuttering problems.
All I can say is that I have the Sonos OS "S2" and my Play:1 is running version "15.9 (Build 75146030)".
I couldn't find anything more specific in the release notes either (https://support.sonos.com/de-de/article/release-notes-for-sonos-s2).
I hope other Sonos users can discover which particular version enables the use of the FLAC feature.

**Comment by dheijl** [comment]
Thanks! I have added this to the Sonos information in the Readme.
