### ISSUE TITLE
can't detect sonos ip addres

### ISSUE THREAD

**Issue by konyong** [dheijl/swyh-rs#81]
its keep telling that the active network is 192.168.1.1 even after i restart several times.
in sonos app the ip address is 192.168.1.14

**Comment by dheijl** [comment]
The "Active Network" dropdown shows the IP address of the network interface in your PC that is selected to detect audio receivers via SSDP. It has no relation to the receiver(s) that swyh-rs is streaming to. In fact if you have multiple streamers you can stream to all of them simultaneously. The dropdown is there to select another network interface if your PC has more than one (physical or virtual):

![afbeelding](https://user-images.githubusercontent.com/2384545/192231608-482b38da-acc5-4d41-a0fa-9ac0a73a3dd9.png)

From the Readme: _By default the network that connects to the internet is chosen (so that on a multihomed Windows machine the most likely interface is selected). If necessary you can choose another network from the network dropdown, for instance if you use a VPN._

**Comment by konyong** [comment]
The  "Active Network" dropdown not showing correct ip address.

**Comment by dheijl** [comment]
Then please provide some relevant information, like the output of ipconfig /all and a swyh-rs logfile.

**Comment by dheijl** [comment]
I will close this now, as without any additional information there is nothing that I can do.
Feel free to reopen this issue if you are ready to provide the output of "ifconfig /all" and the swyh-rs logfile (debug mode if possible).
